server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    driverClassName: org.h2.Driver
    username: root
    password: pass
    hikari:
      connection-timeout: 300000
      idleTimeout: 120000
      max-lifetime: 500000
  jpa:
    show-sql: true
    open-in-view: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

springfox:
  documentation:
    swagger-ui:
      enabled: true

exchangeRate:
  endpoint: http://api.exchangeratesapi.io/v1
  accesKey: 49c64317f3fd1805982401b3d2927ca3