spring:
  application:
    name: exchange-application
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    generate-ddl: false
    hibernate.ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect